In [16]:
import pandas as pd

In [17]:
df=pd.DataFrame({
    "Name":["pavan","harpal","rahul","bhau"],
    "Date":["17-06-2005","15-04-2004","05-12-2026","11-05-2000"]
})
df

     Name        Date
0   pavan  17-06-2005
1  harpal  15-04-2004
2   rahul  05-12-2026
3    bhau  11-05-2000

In [18]:
df["Date"]=pd.to_datetime(
    df["Date"],
    dayfirst=True,
    errors="coerce"
)

In [19]:
df

     Name       Date
0   pavan 2005-06-17
1  harpal 2004-04-15
2   rahul 2026-12-05
3    bhau 2000-05-11

In [20]:
df["Day"]=df["Date"].dt.day
df["Month"]=df["Date"].dt.month
df["Year"]=df["Date"].dt.year

In [21]:
df

     Name       Date  Day  Month  Year
0   pavan 2005-06-17   17      6  2005
1  harpal 2004-04-15   15      4  2004
2   rahul 2026-12-05    5     12  2026
3    bhau 2000-05-11   11      5  2000

In [22]:
# merge()

In [23]:
student=pd.DataFrame(
    {
        "S_id":[101,102,103],
        "Name":["pavan","harpal","bhau"]
    }
)

marks=pd.DataFrame(
    {
        "S_id":[101,102,103],
        "Marks":[85,95,34]
    }
)
result=pd.merge(student,marks,on="S_id")
result

   S_id    Name  Marks
0   101   pavan     85
1   102  harpal     95
2   103    bhau     34

In [ ]:
# join()

In [24]:
student=pd.DataFrame(
    {
        "Name":["pavan","harpal","bhau"]
    },
    index=[101,102,103]
)

marks=pd.DataFrame(
    {
        "Marks":[85,95,34]
    },
    index=[101,102,103],
)
result=student.join(marks)
result

       Name  Marks
101   pavan     85
102  harpal     95
103    bhau     34

In [ ]:
# concat

In [27]:
class_a = pd.DataFrame(
    {
        "Name":["pavan","patel"],
        "Marks":[54,94]
    }
)

class_b = pd.DataFrame(
    {
        "Name":["harpal","bhau"],
        "Marks":[84,42]
    }
)
result = pd.concat(
    [class_a,class_b],
    ignore_index=True
)
result

     Name  Marks
0   pavan     54
1   patel     94
2  harpal     84
3    bhau     42