In [27]:
import pandas as pd
import numpy as np

work = pd.read_csv("case_study_3_workforce_raw.csv")
work

,Employee_Code,Employee_Name,Department,City,Join_Date,Gender,Experience_Years,Monthly_Salary,Performance_Rating,Projects_or_Deals,Annual_Value,Status
0,EMP-2026-001,Aarav Shah,Sales,Ahmedabad,2021-06-14,M,6.0,72000.0,8.7,118,1350000,Active
1,EMP-2026-002,Diya Patel,Marketing,Ahmedabad,2023-01-09,F,3.0,54000.0,9.1,42,610000,Active
2,EMP-2026-003,rohan mehta,Sales,Surat,2022-08-18,M,4.0,61000.0,7.8,93,980000,Active
3,EMP-2026-004,Priya Desai,Finance,Vadodara,2020-02-11,F,7.0,83000.0,9.3,0,0,Active
4,EMP-2026-005,Kabir Joshi,IT,Ahmedabad,2019-11-25,M,8.0,96000.0,8.9,0,0,Active
5,EMP-2026-006,Meera Trivedi,Sales,Rajkot,2024-04-15,F,NaN,47000.0,8.2,66,720000,Active
6,EMP-2026-007,Ishaan Dave,Operations,Ahmedabad,2021-09-03,M,5.0,68000.0,7.5,0,0,Active
7,EMP-2026-008,Nisha Rana,Marketing,Surat,2022-03-21,F,4.0,59000.0,8.8,51,690000,Active
8,EMP-2026-009,Vivaan Shah,Finance,Ahmedabad,2018-07-16,M,9.0,105000.0,9.4,0,0,Active
9,EMP-2026-010,Kavya Mehta,IT,Vadodara,2023-06-12,F,3.0,64000.0,8.5,0,0,Active
10,EMP-2026-011,Arjun Patel,Sales,Ahmedabad,2020-10-05,M,6.0,76000.0,8.0,104,1210000,Active
11,EMP-2026-012,Mahi Shah,Operations,Surat,2024-01-22,F,2.0,45000.0,7.9,0,0,Active
12,EMP-2026-013,Dev Joshi,IT,Rajkot,2021-05-17,M,5.0,79000.0,8.6,0,0,Active
13,EMP-2026-014,Anaya Desai,Marketing,Ahmedabad,2025-02-10,F,1.0,NaN,8.1,28,390000,Active
14,EMP-2026-015,Reyansh Modi,Sales,Vadodara,2017-12-04,M,10.0,118000.0,9.0,132,1510000,Active
15,EMP-2026-016,Sara Khan,Finance,Rajkot,2022-09-19,F,4.0,71000.0,8.7,0,0,Active
16,EMP-2026-017,Dhruv Patel,Operations,Vadodara,2020-06-29,M,7.0,82000.0,7.6,0,0,Active
17,EMP-2026-018,Riya Shah,IT,Surat,2024-07-08,F,2.0,52000.0,8.4,0,0,Active
18,EMP-2026-019,Yash Mehta,Sales,Ahmedabad,31-15-2025,M,1.0,39000.0,7.2,37,410000,Probation
19,EMP-2026-020,Ira Patel,Marketing,Rajkot,2021-12-13,F,5.0,66000.0,9.0,47,730000,Active
20,EMP-2026-021,Om Desai,Finance,Surat,2023-03-27,M,3.0,62000.0,NaN,0,0,Active
21,EMP-2026-022,Myra Joshi,IT,Ahmedabad,2020-08-31,F,6.0,88000.0,9.2,0,0,Active
22,EMP-2026-023,Neil Shah,Operations,Rajkot,2019-04-08,M,8.0,91000.0,8.0,0,0,Active
23,EMP-2026-024,Aanya Patel,Sales,Surat,2023-10-16,F,3.0,56000.0,8.6,78,840000,Active
24,EMP-2026-008,Nisha Rana,Marketing,Surat,2022-03-21,F,4.0,59000.0,8.8,51,690000,Active
25,EMP-2026-015,Reyansh Modi,Sales,Vadodara,2017-12-04,M,10.0,118000.0,9.0,132,1510000,Active

In [28]:
dept = pd.read_csv("case_study_3_department_master.csv")
dept

   Department Business_Unit Department_Head  Target_Growth
0       Sales       Revenue         N. Vora           0.12
1   Marketing        Growth         P. Shah           0.10
2     Finance     Corporate        K. Desai           0.08
3          IT    Technology        R. Mehta           0.11
4  Operations    Operations        S. Patel           0.09

In [29]:
work_clean=work.copy()
work_clean.loc[work_clean.duplicated()]

,Employee_Code,Employee_Name,Department,City,Join_Date,Gender,Experience_Years,Monthly_Salary,Performance_Rating,Projects_or_Deals,Annual_Value,Status
24,EMP-2026-008,Nisha Rana,Marketing,Surat,2022-03-21,F,4.0,59000.0,8.8,51,690000,Active
25,EMP-2026-015,Reyansh Modi,Sales,Vadodara,2017-12-04,M,10.0,118000.0,9.0,132,1510000,Active

In [30]:
work_clean=work_clean.drop_duplicates()

In [31]:
work_clean.loc[work_clean.duplicated()]

Empty DataFrame
Columns: [Employee_Code, Employee_Name, Department, City, Join_Date, Gender, Experience_Years, Monthly_Salary, Performance_Rating, Projects_or_Deals, Annual_Value, Status]
Index: []

In [32]:
work_clean.loc[work_clean.isnull().any(axis=1)]

,Employee_Code,Employee_Name,Department,City,Join_Date,Gender,Experience_Years,Monthly_Salary,Performance_Rating,Projects_or_Deals,Annual_Value,Status
5,EMP-2026-006,Meera Trivedi,Sales,Rajkot,2024-04-15,F,NaN,47000.0,8.2,66,720000,Active
13,EMP-2026-014,Anaya Desai,Marketing,Ahmedabad,2025-02-10,F,1.0,NaN,8.1,28,390000,Active
20,EMP-2026-021,Om Desai,Finance,Surat,2023-03-27,M,3.0,62000.0,NaN,0,0,Active

In [33]:
work_clean["Experience_Years"]=work_clean["Experience_Years"].fillna(work_clean.groupby("Department")["Experience_Years"].transform("mean"))
work_clean["Monthly_Salary"]=work_clean["Monthly_Salary"].fillna(work_clean.groupby("Department")["Monthly_Salary"].transform("mean"))
work_clean["Performance_Rating"]=work_clean["Performance_Rating"].fillna(work_clean.groupby("Department")["Performance_Rating"].transform("mean"))

In [34]:
work_clean.loc[work_clean.isnull().any(axis=1)]

Empty DataFrame
Columns: [Employee_Code, Employee_Name, Department, City, Join_Date, Gender, Experience_Years, Monthly_Salary, Performance_Rating, Projects_or_Deals, Annual_Value, Status]
Index: []

In [35]:
work_clean

,Employee_Code,Employee_Name,Department,City,Join_Date,Gender,Experience_Years,Monthly_Salary,Performance_Rating,Projects_or_Deals,Annual_Value,Status
0,EMP-2026-001,Aarav Shah,Sales,Ahmedabad,2021-06-14,M,6.0,72000.000000,8.700000,118,1350000,Active
1,EMP-2026-002,Diya Patel,Marketing,Ahmedabad,2023-01-09,F,3.0,54000.000000,9.100000,42,610000,Active
2,EMP-2026-003,rohan mehta,Sales,Surat,2022-08-18,M,4.0,61000.000000,7.800000,93,980000,Active
3,EMP-2026-004,Priya Desai,Finance,Vadodara,2020-02-11,F,7.0,83000.000000,9.300000,0,0,Active
4,EMP-2026-005,Kabir Joshi,IT,Ahmedabad,2019-11-25,M,8.0,96000.000000,8.900000,0,0,Active
5,EMP-2026-006,Meera Trivedi,Sales,Rajkot,2024-04-15,F,5.0,47000.000000,8.200000,66,720000,Active
6,EMP-2026-007,Ishaan Dave,Operations,Ahmedabad,2021-09-03,M,5.0,68000.000000,7.500000,0,0,Active
7,EMP-2026-008,Nisha Rana,Marketing,Surat,2022-03-21,F,4.0,59000.000000,8.800000,51,690000,Active
8,EMP-2026-009,Vivaan Shah,Finance,Ahmedabad,2018-07-16,M,9.0,105000.000000,9.400000,0,0,Active
9,EMP-2026-010,Kavya Mehta,IT,Vadodara,2023-06-12,F,3.0,64000.000000,8.500000,0,0,Active
10,EMP-2026-011,Arjun Patel,Sales,Ahmedabad,2020-10-05,M,6.0,76000.000000,8.000000,104,1210000,Active
11,EMP-2026-012,Mahi Shah,Operations,Surat,2024-01-22,F,2.0,45000.000000,7.900000,0,0,Active
12,EMP-2026-013,Dev Joshi,IT,Rajkot,2021-05-17,M,5.0,79000.000000,8.600000,0,0,Active
13,EMP-2026-014,Anaya Desai,Marketing,Ahmedabad,2025-02-10,F,1.0,59666.666667,8.100000,28,390000,Active
14,EMP-2026-015,Reyansh Modi,Sales,Vadodara,2017-12-04,M,10.0,118000.000000,9.000000,132,1510000,Active
15,EMP-2026-016,Sara Khan,Finance,Rajkot,2022-09-19,F,4.0,71000.000000,8.700000,0,0,Active
16,EMP-2026-017,Dhruv Patel,Operations,Vadodara,2020-06-29,M,7.0,82000.000000,7.600000,0,0,Active
17,EMP-2026-018,Riya Shah,IT,Surat,2024-07-08,F,2.0,52000.000000,8.400000,0,0,Active
18,EMP-2026-019,Yash Mehta,Sales,Ahmedabad,31-15-2025,M,1.0,39000.000000,7.200000,37,410000,Probation
19,EMP-2026-020,Ira Patel,Marketing,Rajkot,2021-12-13,F,5.0,66000.000000,9.000000,47,730000,Active
20,EMP-2026-021,Om Desai,Finance,Surat,2023-03-27,M,3.0,62000.000000,9.133333,0,0,Active
21,EMP-2026-022,Myra Joshi,IT,Ahmedabad,2020-08-31,F,6.0,88000.000000,9.200000,0,0,Active
22,EMP-2026-023,Neil Shah,Operations,Rajkot,2019-04-08,M,8.0,91000.000000,8.000000,0,0,Active
23,EMP-2026-024,Aanya Patel,Sales,Surat,2023-10-16,F,3.0,56000.000000,8.600000,78,840000,Active

In [36]:
work_clean.sort_values(by=["Monthly_Salary","Employee_Name","Department"],ascending=False).head()

,Employee_Code,Employee_Name,Department,City,Join_Date,Gender,Experience_Years,Monthly_Salary,Performance_Rating,Projects_or_Deals,Annual_Value,Status
14,EMP-2026-015,Reyansh Modi,Sales,Vadodara,2017-12-04,M,10.0,118000.0,9.0,132,1510000,Active
8,EMP-2026-009,Vivaan Shah,Finance,Ahmedabad,2018-07-16,M,9.0,105000.0,9.4,0,0,Active
4,EMP-2026-005,Kabir Joshi,IT,Ahmedabad,2019-11-25,M,8.0,96000.0,8.9,0,0,Active
22,EMP-2026-023,Neil Shah,Operations,Rajkot,2019-04-08,M,8.0,91000.0,8.0,0,0,Active
21,EMP-2026-022,Myra Joshi,IT,Ahmedabad,2020-08-31,F,6.0,88000.0,9.2,0,0,Active

In [37]:
av=work_clean.groupby("Department")[["Performance_Rating","Monthly_Salary"]].mean()

In [38]:
av.sort_values(by="Monthly_Salary",ascending=False).head(1)

            Performance_Rating  Monthly_Salary
Department
Finance               9.133333         80250.0

In [39]:
work_clean["Employee_Name"] = work_clean["Employee_Name"].str.title().str.strip()
work_clean["Employee_Number"] = (work_clean["Employee_Code"].str.extract(r"(\d+)$")[0].astype(int))
work_clean[["Employee_Code", "Employee_Name", "Employee_Number"]]

   Employee_Code  Employee_Name  Employee_Number
0   EMP-2026-001     Aarav Shah                1
1   EMP-2026-002     Diya Patel                2
2   EMP-2026-003    Rohan Mehta                3
3   EMP-2026-004    Priya Desai                4
4   EMP-2026-005    Kabir Joshi                5
5   EMP-2026-006  Meera Trivedi                6
6   EMP-2026-007    Ishaan Dave                7
7   EMP-2026-008     Nisha Rana                8
8   EMP-2026-009    Vivaan Shah                9
9   EMP-2026-010    Kavya Mehta               10
10  EMP-2026-011    Arjun Patel               11
11  EMP-2026-012      Mahi Shah               12
12  EMP-2026-013      Dev Joshi               13
13  EMP-2026-014    Anaya Desai               14
14  EMP-2026-015   Reyansh Modi               15
15  EMP-2026-016      Sara Khan               16
16  EMP-2026-017    Dhruv Patel               17
17  EMP-2026-018      Riya Shah               18
18  EMP-2026-019     Yash Mehta               19
19  EMP-2026-020      Ira Patel               20
20  EMP-2026-021       Om Desai               21
21  EMP-2026-022     Myra Joshi               22
22  EMP-2026-023      Neil Shah               23
23  EMP-2026-024    Aanya Patel               24

In [40]:
department_distribution = (work_clean["Department"].value_counts().reset_index())
print(department_distribution)
department_distribution.columns = ["Department", "Employee_Count"]
department_distribution["Percentage"] = (department_distribution["Employee_Count"]/ len(work_clean) * 100).round(2)
print(department_distribution)

   Department  count
0       Sales      7
1          IT      5
2   Marketing      4
3     Finance      4
4  Operations      4
   Department  Employee_Count  Percentage
0       Sales               7       29.17
1          IT               5       20.83
2   Marketing               4       16.67
3     Finance               4       16.67
4  Operations               4       16.67

In [41]:
gender_department = pd.crosstab(work_clean["Department"],work_clean["Gender"])
gender_department

Gender      F  M
Department
Finance     2  2
IT          3  2
Marketing   4  0
Operations  1  3
Sales       2  5

In [51]:
work_clean["Join_Date"] = pd.to_datetime(
    work_clean["Join_Date"],
    errors="coerce"
)

work_clean["Join_Year"] = work_clean["Join_Date"].dt.year

joining_by_year = (
    work_clean["Join_Year"]
    .value_counts()
    .sort_index()
)

print(joining_by_year)

Join_Year
2017.0    1
2018.0    1
2019.0    2
2020.0    4
2021.0    4
2022.0    3
2023.0    4
2024.0    3
2025.0    1
Name: count, dtype: int64

In [55]:
most_joining_year = joining_by_year.idxmax()
maximum_joining = joining_by_year.max()

print(most_joining_year)
print(maximum_joining)

merged_df = pd.merge(work_clean,dept,on="Department",how="left")

department_master_summary = merged_df.groupby(["Department", "Business_Unit", "Department_Head"]).agg(
    Employee_Count=("Employee_Code", "count"),
    Average_Salary=("Monthly_Salary", "mean")
).round(2)

display(department_master_summary)

2020.0
4

                                          Employee_Count  Average_Salary
Department Business_Unit Department_Head
Finance    Corporate     K. Desai                      4        80250.00
IT         Technology    R. Mehta                      5        75800.00
Marketing  Growth        P. Shah                       4        59666.67
Operations Operations    S. Patel                      4        71500.00
Sales      Revenue       N. Vora                       7        67000.00

                  Experience_Years  Monthly_Salary
Experience_Years          1.000000        0.909733
Monthly_Salary            0.909733        1.000000

0.9097329145836692

In [61]:
correlation = work_clean[["Experience_Years", "Monthly_Salary"]].corr()
display(correlation)

                  Experience_Years  Monthly_Salary
Experience_Years          1.000000        0.909733
Monthly_Salary            0.909733        1.000000

In [62]:
corr_value = work_clean["Experience_Years"].corr(work_clean["Monthly_Salary"])
corr_value

0.9097329145836692