In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("students_type_conversion.csv")

In [3]:
df

,StudentID,Name,Age,Marks,JoinDate,Active,City,StudyTime,Fees
0,ST101,Aarav,20,85,2025-01-15,Yes,Delhi,2 days,45000.50
1,ST102,Diya,19,92,18/02/2025,No,Mumbai,1 day,52000.00
2,ST103,Rohan,twenty-one,78,2025/03/05,yes,Pune,3 days,48000.75
3,ST104,Priya,20,88,"March 12, 2025",NO,Delhi,5 hours,50000.00
4,ST105,Arjun,22,Absent,2025-04-01,Y,Delhi,2 days 4 hours,61000.00
5,ST106,Neha,NaN,81,01-05-2025,N,Jaipur,1 day 12 hours,47000.25
6,ST107,Rahul,20,67,2025-13-01,Yes,Delhi,invalid,42000.00
7,ST108,Kavya,20,87,2025-06-10,No,Mumbai,4 days,53000.00
8,ST109,Vivek,22,84,10 Jul 2025,TRUE,Pune,36 hours,49500.00
9,ST110,Meera,21,76,2025-08-20,FALSE,Jaipur,2 days,46000.00
10,ST111,Ishaan,19,91.5,2025-09-02,1,Delhi,12 hours,55000.80
11,ST112,Ananya,20,89,02/10/2025,0,Mumbai,NaN,57500.00
12,ST113,Kabir,21,73,2025-11-11,yes,Pune,1 day,44000.00
13,ST114,Sara,unknown,95,not available,no,Delhi,3 days,62000.00
14,ST115,Dev,23,82,2025-12-05,NaN,Jaipur,48 hours,51000.40

In [4]:
df.dtypes

StudentID     object
Name          object
Age           object
Marks         object
JoinDate      object
Active        object
City          object
StudyTime     object
Fees         float64
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  15 non-null     object
 1   Name       15 non-null     object
 2   Age        14 non-null     object
 3   Marks      15 non-null     object
 4   JoinDate   15 non-null     object
 5   Active     14 non-null     object
 6   City       15 non-null     object
 7   StudyTime  14 non-null     object
 8   Fees       15 non-null     float64
dtypes: float64(1), object(8)
memory usage: 1.2+ KB

In [6]:
df1=df.copy()
df1["StudentID"]=df1["StudentID"].astype("string") #convert into string
df1["StudentID"].dtype

string[python]

In [7]:
df1["Fees"]=df1["Fees"].astype(float) #convert into float
df1["Fees"].dtype

dtype('float64')

In [8]:
df1.dtypes

StudentID    string[python]
Name                 object
Age                  object
Marks                object
JoinDate             object
Active               object
City                 object
StudyTime            object
Fees                float64
dtype: object

In [9]:
df1["City"]=df1["City"].astype("category") #convert into category
df1["City"].dtype

CategoricalDtype(categories=['Delhi', 'Jaipur', 'Mumbai', 'Pune'], ordered=False, categories_dtype=object)

In [10]:
df1["City"].cat.categories # shows all category

Index(['Delhi', 'Jaipur', 'Mumbai', 'Pune'], dtype='object')

In [11]:
df1["Age"] = pd.to_numeric(df1["Age"],errors="coerce").astype("Int64") # convet into int and remove wrong values = NaN 
df1["Age"]

0       20
1       19
2     <NA>
3       20
4       22
5     <NA>
6       20
7       20
8       22
9       21
10      19
11      20
12      21
13    <NA>
14      23
Name: Age, dtype: Int64

In [12]:
age_numeric = pd.to_numeric(df["Age"],errors="raise") # exit when error comes

ValueError: Unable to parse string "twenty-one" at position 2

In [ ]:
age_numeric1 = pd.to_numeric(df["Age"],errors="ignore") # ignore not convertable values

In [ ]:
df1["JoinDate"] = pd.to_datetime(
    df1["JoinDate"],
    format="mixed",
    errors="coerce") # convet into date formate
df1["JoinDate"]

In [17]:
df1["StudyTime"] = pd.to_timedelta(
    df1["StudyTime"],
    errors="coerce") # convert into timedelta(day & hours) type
df1["StudyTime"]

0    2 days 00:00:00
1    1 days 00:00:00
2    3 days 00:00:00
3    0 days 05:00:00
4    2 days 04:00:00
5    1 days 12:00:00
6                NaT
7    4 days 00:00:00
8    1 days 12:00:00
9    2 days 00:00:00
10   0 days 12:00:00
11               NaT
12   1 days 00:00:00
13   3 days 00:00:00
14   2 days 00:00:00
Name: StudyTime, dtype: timedelta64[ns]

In [23]:
active_map = {
    "yes":True,"y":True,"true":True,"1":True,
    "no":False,"n":False,"false":False,"0":False
}
df1["Active"] = (
    df1["Active"]
    .astype("string")
    .str.strip()
    .str.lower()
    .fillna("False")
    .map(active_map)
    .astype("boolean")
) # convert into boolean

In [24]:
df1["Active"]

0      True
1     False
2      True
3     False
4      True
5     False
6      True
7     False
8      True
9     False
10     True
11    False
12     True
13    False
14     <NA>
Name: Active, dtype: boolean

In [25]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  15 non-null     string
 1   Name       15 non-null     object
 2   Age        12 non-null     Int64
 3   Marks      15 non-null     object
 4   JoinDate   15 non-null     object
 5   Active     14 non-null     boolean
 6   City       15 non-null     category
 7   StudyTime  13 non-null     timedelta64[ns]
 8   Fees       15 non-null     float64
dtypes: Int64(1), boolean(1), category(1), float64(1), object(3), string(1), timedelta64[ns](1)
memory usage: 1.2+ KB

In [16]:
df1

,StudentID,Name,Age,Marks,JoinDate,Active,City,StudyTime,Fees
0,ST101,Aarav,20,85,2025-01-15,True,Delhi,2 days,45000.50
1,ST102,Diya,19,92,18/02/2025,False,Mumbai,1 day,52000.00
2,ST103,Rohan,<NA>,78,2025/03/05,True,Pune,3 days,48000.75
3,ST104,Priya,20,88,"March 12, 2025",False,Delhi,5 hours,50000.00
4,ST105,Arjun,22,Absent,2025-04-01,True,Delhi,2 days 4 hours,61000.00
5,ST106,Neha,<NA>,81,01-05-2025,False,Jaipur,1 day 12 hours,47000.25
6,ST107,Rahul,20,67,2025-13-01,True,Delhi,invalid,42000.00
7,ST108,Kavya,20,87,2025-06-10,False,Mumbai,4 days,53000.00
8,ST109,Vivek,22,84,10 Jul 2025,True,Pune,36 hours,49500.00
9,ST110,Meera,21,76,2025-08-20,False,Jaipur,2 days,46000.00
10,ST111,Ishaan,19,91.5,2025-09-02,True,Delhi,12 hours,55000.80
11,ST112,Ananya,20,89,02/10/2025,False,Mumbai,NaN,57500.00
12,ST113,Kabir,21,73,2025-11-11,True,Pune,1 day,44000.00
13,ST114,Sara,<NA>,95,not available,False,Delhi,3 days,62000.00
14,ST115,Dev,23,82,2025-12-05,<NA>,Jaipur,48 hours,51000.40