In [3]:
import pandas as pd

In [4]:
student={
    'roll':[1,2,3,4,5],
    'name':['pavan','harpal','bhau','swati','rekha'],
    'marsk':[85,45,65,78,25]
    
}
df=pd.DataFrame(student)
df

   roll    name  marsk
0     1   pavan     85
1     2  harpal     45
2     3    bhau     65
3     4   swati     78
4     5   rekha     25

In [5]:
import os 
print(os.getcwd())

C:\Users\ex503_55

In [6]:
print(os.listdir())

['.android', '.dbshell', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.ms-ad', '.spyder-py3', '.vscode', '3D Objects', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'Desktop', 'Documents', 'Downloads', 'Ds_day_2.ipynb', 'Favorites', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{cd33cd70-546e-11ef-a86a-a08cfdc946d3}.TM.blf', 'NTUSER.DAT{cd33cd70-546e-11ef-a86a-a08cfdc946d3}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{cd33cd70-546e-11ef-a86a-a08cfdc946d3}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Pictures', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Untitled Folder', 'Untitled Folder 1', 'Untitled.ipynb', 'Videos']

In [7]:
df = pd.read_csv("students.csv")
df

    Roll            Name  Age  Marks
0      1    Aarav Sharma   18     85
1      2      Diya Patel   19     92
2      3    Vihaan Singh   18     78
3      4    Ananya Gupta   20     88
4      5     Arjun Mehta   19     95
5      6      Isha Verma   18     81
6      7     Kabir Joshi   20     74
7      8      Meera Nair   19     90
8      9       Rohan Das   18     69
9     10  Sneha Kulkarni   20     87
10    11      Aditya Rao   19     93
11    12      Kavya Iyer   18     76
12    13    Rahul Kapoor   20     84
13    14      Priya Shah   19     91
14    15   Yash Malhotra   18     79

In [10]:
df = pd.read_json("students.json")
df

    Roll            Name  Age  Marks
0      1    Aarav Sharma   18     85
1      2      Diya Patel   19     92
2      3    Vihaan Singh   18     78
3      4    Ananya Gupta   20     88
4      5     Arjun Mehta   19     95
5      6      Isha Verma   18     81
6      7     Kabir Joshi   20     74
7      8      Meera Nair   19     90
8      9       Rohan Das   18     69
9     10  Sneha Kulkarni   20     87
10    11      Aditya Rao   19     93
11    12      Kavya Iyer   18     76
12    13    Rahul Kapoor   20     84
13    14      Priya Shah   19     91
14    15   Yash Malhotra   18     79

In [12]:
df = pd.read_excel("students.xlsx")
df

    Roll            Name  Age  Marks
0      1    Aarav Sharma   18     85
1      2      Diya Patel   19     92
2      3    Vihaan Singh   18     78
3      4    Ananya Gupta   20     88
4      5     Arjun Mehta   19     95
5      6      Isha Verma   18     81
6      7     Kabir Joshi   20     74
7      8      Meera Nair   19     90
8      9       Rohan Das   18     69
9     10  Sneha Kulkarni   20     87
10    11      Aditya Rao   19     93
11    12      Kavya Iyer   18     76
12    13    Rahul Kapoor   20     84
13    14      Priya Shah   19     91
14    15   Yash Malhotra   18     79

In [13]:
df = pd.read_csv("students.csv")
df

    Roll            Name  Age  Marks
0      1    Aarav Sharma   18     85
1      2      Diya Patel   19     92
2      3    Vihaan Singh   18     78
3      4    Ananya Gupta   20     88
4      5     Arjun Mehta   19     95
5      6      Isha Verma   18     81
6      7     Kabir Joshi   20     74
7      8      Meera Nair   19     90
8      9       Rohan Das   18     69
9     10  Sneha Kulkarni   20     87
10    11      Aditya Rao   19     93
11    12      Kavya Iyer   18     76
12    13    Rahul Kapoor   20     84
13    14      Priya Shah   19     91
14    15   Yash Malhotra   18     79

In [15]:
df.head() #first five records

   Roll          Name  Age  Marks
0     1  Aarav Sharma   18     85
1     2    Diya Patel   19     92
2     3  Vihaan Singh   18     78
3     4  Ananya Gupta   20     88
4     5   Arjun Mehta   19     95

In [16]:
df.head(2) # first 2 records

   Roll          Name  Age  Marks
0     1  Aarav Sharma   18     85
1     2    Diya Patel   19     92

In [17]:
df.tail() # last five records

    Roll           Name  Age  Marks
10    11     Aditya Rao   19     93
11    12     Kavya Iyer   18     76
12    13   Rahul Kapoor   20     84
13    14     Priya Shah   19     91
14    15  Yash Malhotra   18     79

In [18]:
df.tail(3) # last 3 records

    Roll           Name  Age  Marks
12    13   Rahul Kapoor   20     84
13    14     Priya Shah   19     91
14    15  Yash Malhotra   18     79

In [19]:
df.shape # rows and col

(15, 4)

In [22]:
df.sample() # gives random data

    Roll        Name  Age  Marks
13    14  Priya Shah   19     91

In [23]:
df.sample(3) # gives 3 random data

   Roll            Name  Age  Marks
8     9       Rohan Das   18     69
4     5     Arjun Mehta   19     95
9    10  Sneha Kulkarni   20     87

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Roll    15 non-null     int64
 1   Name    15 non-null     object
 2   Age     15 non-null     int64
 3   Marks   15 non-null     int64
dtypes: int64(3), object(1)
memory usage: 612.0+ bytes