In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["Aarav", "Diya", "Rohan", "Priya", "Kabir", "Meera"],
    "Course": ["MCA", "MBA", "MCA", "MCA", "MBA", "MCA"],
    "Gender": ["M", "F", "M", "F", "M", "F"],
    "Marks": [82, 91, 76, 88, 69, 95],
    "Study_Hours": [4, 6, 3, 5, 2, 7]
})
df

    Name Course Gender  Marks  Study_Hours
0  Aarav    MCA      M     82            4
1   Diya    MBA      F     91            6
2  Rohan    MCA      M     76            3
3  Priya    MCA      F     88            5
4  Kabir    MBA      M     69            2
5  Meera    MCA      F     95            7

In [3]:
print(df["Course"].value_counts())

Course
MCA    4
MBA    2
Name: count, dtype: int64

In [4]:
print(df[["Course","Gender"]].value_counts())

Course  Gender
MCA     F         2
        M         2
MBA     F         1
        M         1
Name: count, dtype: int64

In [5]:
df["Course"].value_counts(normalize=True)

Course
MCA    0.666667
MBA    0.333333
Name: proportion, dtype: float64

In [6]:
df["Course"].value_counts(normalize=True)*100

Course
MCA    66.666667
MBA    33.333333
Name: proportion, dtype: float64

In [7]:
round(df["Course"].value_counts(normalize=True)*100)

Course
MCA    67.0
MBA    33.0
Name: proportion, dtype: float64

In [8]:
df[["Course","Gender"]].value_counts(normalize=True)*100

Course  Gender
MCA     F         33.333333
        M         33.333333
MBA     F         16.666667
        M         16.666667
Name: proportion, dtype: float64

In [9]:
df["Course"].value_counts(normalize=False)

Course
MCA    4
MBA    2
Name: count, dtype: int64

In [10]:
pd.crosstab(df["Course"],df["Gender"])

Gender  F  M
Course
MBA     1  1
MCA     2  2

In [11]:
pd.crosstab(df["Course"],df["Gender"],margins=True)

Gender  F  M  All
Course
MBA     1  1    2
MCA     2  2    4
All     3  3    6

In [12]:
pd.pivot_table(
    df,
    values="Marks",
    index="Course",
    columns="Gender",
    aggfunc="mean"
)

Gender     F     M
Course
MBA     91.0  69.0
MCA     91.5  79.0

In [13]:
pd.pivot_table(
    df,
    values="Marks",
    index="Gender",
    columns="Course",
    aggfunc="mean"
)

Course   MBA   MCA
Gender
F       91.0  91.5
M       69.0  79.0

In [14]:
df.pivot_table(
    values="Marks",
    index="Course",
    aggfunc=["mean","max"]
)

         mean   max
        Marks Marks
Course
MBA     80.00    91
MCA     85.25    95

In [15]:
df.pivot_table(
    values="Marks",
    index="Course",
    columns="Gender",
    aggfunc=["mean","max"]
)

        mean       max
Gender     F     M   F   M
Course
MBA     91.0  69.0  91  69
MCA     91.5  79.0  95  82

In [16]:
numeric_df = df[["Marks","Study_Hours"]]
print(numeric_df.corr())

                Marks  Study_Hours
Marks        1.000000     0.990017
Study_Hours  0.990017     1.000000

In [17]:
df[["Marks","Study_Hours"]].corr()

                Marks  Study_Hours
Marks        1.000000     0.990017
Study_Hours  0.990017     1.000000

In [18]:
df1 = pd.DataFrame({
    "Name": ["Aarav", "Diya", "Rohan", "Priya", "Kabir", "Meera"],
    "Course": ["MCA", "MBA", "MCA", "MCA", "MBA", "MCA"],
    "Gender": [1, 0, 1, 0, 1, 0],
    "Marks": [82, 91, 76, 88, 69, 95],
    "Study_Hours": [4, 6, 3, 5, 2, 7]
})
df1[["Marks","Gender"]].corr()

           Marks    Gender
Marks   1.000000 -0.878083
Gender -0.878083  1.000000