In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["  Aarav Shah  ", "diya PATEL", "Rohan Mehta", "priya joshi"],
    "Email": ["AARAV@GMAIL.COM", "diya@yahoo.com", "rohan@gmail.com", "priya@outlook.com"],
    "Course_Code": ["MCA-101", "BCA-205", "MCA-310", "BSC-115"]
})

In [3]:
df

             Name              Email Course_Code
0    Aarav Shah      AARAV@GMAIL.COM     MCA-101
1      diya PATEL     diya@yahoo.com     BCA-205
2     Rohan Mehta    rohan@gmail.com     MCA-310
3     priya joshi  priya@outlook.com     BSC-115

In [13]:
df["Email"] = df["Email"].str.lower()  #convert into lowercase

In [14]:
df["Course_Code"] = df["Course_Code"].str.upper() # convert into uppercase

In [15]:
df["Name"] = df["Name"].astype("string").str.strip() # remove whitespaces

In [16]:
df

          Name              Email Course_Code
0   aarav shah    aarav@gmail.com     MCA-101
1   diya patel     diya@yahoo.com     BCA-205
2  rohan mehta    rohan@gmail.com     MCA-310
3  priya joshi  priya@outlook.com     BSC-115

In [18]:
price = pd.Series(["₹1,200", "₹850", "₹2,500"])
price

0    ₹1,200
1      ₹850
2    ₹2,500
dtype: object

In [19]:
price=(price.astype("string")
       .str.replace("₹","",regex=False)
       .str.replace(",","",regex=False)
      ) #remove ₹ and ,

In [20]:
price

0    1200
1     850
2    2500
dtype: string

In [21]:
df["Email"].str.lower().str.contains("gmail") # search values

0     True
1    False
2     True
3    False
Name: Email, dtype: bool

In [22]:
df[df["Email"].str.lower().str.contains("gmail",na=False)] #shows only gmail values

          Name            Email Course_Code
0   aarav shah  aarav@gmail.com     MCA-101
2  rohan mehta  rohan@gmail.com     MCA-310

In [24]:
df["Course"] = df["Course_Code"].str.extract(r"([A-Z]+)")
df["Number"] = df["Course_Code"].str.extract(r"(\d+)")

df[["Course_Code", "Course", "Number"]] # extract part of Course_Code

  Course_Code Course Number
0     MCA-101    MCA    101
1     BCA-205    BCA    205
2     MCA-310    MCA    310
3     BSC-115    BSC    115

In [28]:
df["City"] = ["Ahm.edabad","sur.at","BARODA","mumBai"]
df["City"] = (
    df["City"]
      .astype("string")
      .str.strip()
      .str.lower()
      .str.replace(".", "", regex=False)
)

In [29]:
df

          Name              Email Course_Code Course Number       City
0   aarav shah    aarav@gmail.com     MCA-101    MCA    101  ahmedabad
1   diya patel     diya@yahoo.com     BCA-205    BCA    205      surat
2  rohan mehta    rohan@gmail.com     MCA-310    MCA    310     baroda
3  priya joshi  priya@outlook.com     BSC-115    BSC    115     mumbai